language: node_js
cache:
    npm: false
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: r4bMeHdS9vdDWuL3ax+va5YoaZKmn5MxsXNxMgnT7lrk4AFkb2wr+17+4zDalQFyt7zyqM0HJzGXRYGTiG4kow6Jk2P55wv3LeiNJxpTBOGYfKTldjLZKIxxaqJLYJ40JhlfuA+TaTj0JWVsohz5CQJxO1O7Z+/xq/0ZwHVIhDNwW5XdFDdCdBZRQMV7XKSynGAB7L0pdhASSdl4laQTxjL/6A3B0Sr9rwO5Nd8YbzZpUPQ5opTLXfln2JSMTiAEtxgLS2ARu5Aa+9qfIA5VTDXzcyYAE+uErjIXeUfNRbTCJuizNQQZOoeMR36tam0cOu+B0qt0FWqCECOlmN12tL0TpY54vqsJfS4AIUT4dm2LpjPKCKZn4jIZxVJe3uxTRKZrWiDSaKUmnuoRIoTCPh4JMYc7t6pxP/4kKcAEpw4OxYS0eERG4RXKSJx9I2szqvJ+9nS/eAO3AC/5KWn+o+x1ebnjNgmGk/7BQbgdEOm1wsUazpEAg/nkL4b5EW6IEzUJm8V31NO1OxoAs+U0NLgOu3OKys0KxjwpzTFtQ0bvQoNcy715Y6JfLwZQFOTOUM6OjMXhAE4AF6mt/SYHE7iTY1I+TZxt71RLN5+t0DQSyNHQ/VStx1nTg9HOjs35ZxxJYG2y5fbsBBmeV8wGY1iX9GAsTO2oGgfAzUIuMQs=
